export const BottomProducts = [
        {
            id: 1,
            title : 'Shisha work capri',
            color : 'black',
            type : 'bottom',
            category : 'bottom',
            fabric : 'lawn',
            qunatity : '20',
            season  :'summer',
            inStock : true,
            completeSuitPrice : 3240,
            images : [
                "./assests/images/bottoms/BottomBlackFull.jpg",
                "./assests/images/bottoms/BottomBlackZoom.jpg",
            ],
        },
        {
            id: 2,
            title : 'Shisha work capri',
            color : 'green',
            type : 'bottom',
            category : 'bottom',
            fabric : 'lawn',
            qunatity : '20',
            season  :'summer',
            inStock : true,
            completeSuitPrice : 3460,
            images : [
                "./assests/images/bottoms/BottomGreenFull.jpg",
                "./assests/images/bottoms/BottomGreenZoom.jpg",
            ],
        },
        {
            id: 3,
            title : 'Shisha work capri',
            color : 'red',
            type : 'bottom',
            category : 'bottom',
            fabric : 'lawn',
            qunatity : '20',
            season  :'summer',
            inStock : true,
            completeSuitPrice : 3780,
            images : [
                "./assests/images/bottoms/BottomRedFull.jpg",
                "./assests/images/bottoms/BottomRedZoom.jpg",
            ],
        },
        {
            id: 4,
            title : 'Shisha work capri',
            color : 'white',
            type : 'bottom',
            category : 'bottom',
            fabric : 'lawn',
            qunatity : '20',
            season  :'summer',
            inStock : true,
            completeSuitPrice : 3100,
            images : [
                "./assests/images/bottoms/BottomWhiteFull.jpg",
                "./assests/images/bottoms/BottomWhiteZoom.jpg",
            ],
        },
        {
            id: 5,
            title : 'sleek 3',
            color : 'beige',
            type : 'bottom',
            category : 'bottom',
            fabric : 'lawn',
            qunatity : '20',
            season  :'summer',
            inStock : true,
            completeSuitPrice : 1940,
            images : [
                "./assests/images/bottoms/BottomBeigeFull.jpg",
                "./assests/images/bottoms/BottomBeigeZoom.jpg",
            ],
        },
        {
            id: 6,
            title : 'rangoli shalwar',
            color : 'shocking pink',
            type : 'bottom',
            category : 'bottom',
            fabric : 'lawn',
            qunatity : '20',
            season  :'summer',
            inStock : true,
            completeSuitPrice : 5000,
            images : [
                "./assests/images/bottoms/BottomPink2.jpg",
                "./assests/images/bottoms/BottomPink1.jpg",
            ],
        },
        {
            id: 7,
            title : 'rangoli shalwar',
            color : 'shocking pink',
            type : 'bottom',
            category : 'bottom',
            fabric : 'lawn',
            qunatity : '20',
            season  :'summer',
            inStock : true,
            completeSuitPrice : 5000,
            images : [
                "./assests/images/bottoms/BottomWhite11.jpg",
                "./assests/images/bottoms/BottomWhite_11.jpg",
            ],
        },
]