export const CasualProducts = [
    {
        id: 1,
        title : 'Shadow Work',
        color : 'aqua',
        type : 'embrodered',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 14105,
        customSelectionPrice : {
            shirt : 3250,
            back : 3855,
            dupatta : 5575,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/shadowWorkAquaFront.jpg",
            "./assests/images/casuals/shadowWorkAquaBack.jpg",
            "./assests/images/casuals/shadowWorkAquaSide.jpg",
            "./assests/images/casuals/shadowWorkAquaZoom.jpg",
        ],
    },
    {
        id: 2,
        title : 'arezu range',
        color : 'black',
        type : 'chiffon',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 17675,
        customSelectionPrice : {
            shirt : 5960,
            back : 4440,
            dupatta : 5850,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/arezuRangeBlackFull.jpg",
             "./assests/images/casuals/arezuRangeBlackBack.jpg",
             "./assests/images/casuals/arezuRangeBlackSide.jpg",
            "./assests/images/casuals/arezuRangeBlackZoom.jpg",
        ],
    },
    {
        id: 3,
        title : 'arezu range',
        color : 'white',
        type : 'chiffon',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 17600,
        customSelectionPrice : {
            shirt : 5960,
            back : 4440,
            dupatta : 5850,
            shalwar : 1350,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/arezuWhiteFront.jpg",
            "./assests/images/casuals/arezuWhiteSide.jpg",
            "./assests/images/casuals/arezuWhiteZoom.jpg",
        ],
    },
    {
        id: 4,
        title : 'bahar gul',
        color : 'blue',
        type : 'chiffon',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 12705,
        customSelectionPrice : {
            shirt : 2840,
            back : 2715,
            dupatta : 5725,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/baharGulBlueFull.jpg",
            "./assests/images/casuals/baharGulBlueBack.jpg",
            "./assests/images/casuals/baharGulBlueSide.jpg",
            "./assests/images/casuals/baharGulBlueZoom.jpg",
        ],
    },
    {
        id: 5,
        title : 'banjara',
        color : 'orange',
        type : 'embroidered',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 12815,
        customSelectionPrice : {
            shirt : 2780,
            back : 2835,
            dupatta : 5775,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/banjaraOrangeFull.jpg",
            "./assests/images/casuals/banjaraOrangeback.jpg",
            "./assests/images/casuals/banjaraOrangeSide.jpg",
            "./assests/images/casuals/banjaraOrangeZoom.jpg",
        ],
    },
    {
        id: 6,
        title : 'botanic rhythm',
        color : 'cream',
        type : 'embroidered',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 15030,
        customSelectionPrice : {
            shirt : 4530,
            back : 3075,
            dupatta : 6000,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/botanicCreamFull.jpg",
            "./assests/images/casuals/botanicCreamBack.jpg",
            "./assests/images/casuals/botanicCreamSide.jpg",
            "./assests/images/casuals/botanicCreamZoom.jpg",
        ],
    },
    {
        id: 7,
        title : 'chand bagh',
        color : 'black',
        type : 'embroidered',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 15125,
        customSelectionPrice : {
            shirt : 7550,
            back : 0,
            dupatta : 6150,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/chandBaghBlackFull.jpg",
            "./assests/images/casuals/chandBaghBlackSide.jpg",
            "./assests/images/casuals/chandBaghBlackZoom.jpg",
        ],
    },
    {
        id: 8,
        title : 'chand bagh',
        color : 'blue',
        type : 'embroidered',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 15175,
        customSelectionPrice : {
            shirt : 7475,
            back : 0,
            dupatta : 6275,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/chandbaghBlueFull.jpg",
            "./assests/images/casuals/chandbaghBlueBack.jpg",
            "./assests/images/casuals/chandbaghBlueSide.jpg",
            "./assests/images/casuals/chandbaghBlueZoom.jpg",
        ],
    },
    {
        id: 9,
        title : 'dolman range',
        color : 'black',
        type : 'embroidered',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 14090,
        customSelectionPrice : {
            shirt : 3390,
            back : 3750,
            dupatta : 5525,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/dolmanRangeBlackFront.jpg",
            "./assests/images/casuals/dolmanRangeBlackBack.jpg",
            "./assests/images/casuals/dolmanRangeBlackSide.jpg",
            "./assests/images/casuals/dolmanRangeBlackZoom.jpg",
        ],
    },
    {
        id: 10,
        title : 'dolman',
        color : 'black',
        type : 'embroidered',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 14100,
        customSelectionPrice : {
            shirt : 3390,
            back : 3510,
            dupatta : 5775,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/dolmenBlackfull.jpg",
            "./assests/images/casuals/dolmenBlack.jpg",
            "./assests/images/casuals/dolmenBlack2.jpg",
        ],
    },
    {
        id: 11,
        title : 'dolman',
        color : 'white',
        type : 'embroidered',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 14015,
        customSelectionPrice : {
            shirt : 3390,
            back : 3750,
            dupatta : 5525,
            shalwar : 1350,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/dolmenWhiteFull.jpg",
            "./assests/images/casuals/dolmenWhiteSide.jpg",
            "./assests/images/casuals/dolmenWhiteZoom.jpg",
        ],
    },
    {
        id: 12,
        title : 'ethnic glow',
        color : 'black',
        type : 'embroidered',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 13843,
        customSelectionPrice : {
            shirt : 3750,
            back : 2817,
            dupatta : 5850,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/ethnicGlowBlackFull.jpg",
            "./assests/images/casuals/ethnicGlowBlackBack.jpg",
            "./assests/images/casuals/ethnicGlowBlackSide.jpg",
            "./assests/images/casuals/ethnicGlowBlackZoom.jpg",
        ],
    },
    {
        id: 13,
        title : 'ethnic glow',
        color : 'mustered',
        type : 'embroidered',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 13843,
        customSelectionPrice : {
            shirt : 3750,
            back : 2817,
            dupatta : 5850,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/ethnicGlowMusteredFull.jpg",
            "./assests/images/casuals/ethnicGlowMusteredBack.jpg",
            "./assests/images/casuals/ethnicGlowMusteredZoom.jpg",
        ],
    },
    {
        id: 14,
        title : 'flora garland',
        color : 'blue',
        type : 'embroidered',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 11640,
        customSelectionPrice : {
            shirt : 2400,
            back : 2040,
            dupatta : 5775,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/floraGarlandBlueFull.jpg",
            "./assests/images/casuals/floraGarlandBlueBack.jpg",
            "./assests/images/casuals/floraGarlandBlueSide.jpg",
            "./assests/images/casuals/floraGarlandBlueZoom.jpg",
        ],
    },
    {
        id: 15,
        title : 'glowing flora',
        color : 'pink',
        type : 'embroidered',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 14100,
        customSelectionPrice : {
            shirt : 6625,
            back : 0,
            dupatta : 6050,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/glowingFloraPinkFull.jpg",
            "./assests/images/casuals/glowingFloraPinkBack.jpg",
            "./assests/images/casuals/glowingFloraPinkSide.jpg",
            "./assests/images/casuals/glowingFloraPinkZoom.jpg",
        ],
    },
    {
        id: 16,
        title : 'hangaria range',
        color : 'blue',
        type : 'embroidered',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 12705,
        customSelectionPrice : {
            shirt : 2610,
            back : 2820,
            dupatta : 5850,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/hangriyanBlueFull.jpg",
            "./assests/images/casuals/hangriyanBlueBlack.jpg",
            "./assests/images/casuals/hangriyanBlueSide.jpg",
            "./assests/images/casuals/hangriyanBlueZoom.jpg",
        ],
    },
    {
        id: 17,
        title : 'shadow work',
        color : 'green',
        type : 'embroidered',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 14150,
        customSelectionPrice : {
            shirt : 3250,
            back : 3825,
            dupatta : 5650,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/shadowWorkGreenFront.jpg",
            "./assests/images/casuals/shadowWorkGreenSide.jpg",
            "./assests/images/casuals/shadowWorkGreenZoom.jpg",
        ],
    },
    {
        id: 18,
        title : 'turkish flowers',
        color : 'white',
        type : 'embroidered',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 15200,
        customSelectionPrice : {
            shirt : 5120,
            back : 3030,
            dupatta : 5700,
            shalwar : 1350,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/turkishWhitefull.jpg",
            "./assests/images/casuals/turkishWhite.jpg",
            "./assests/images/casuals/turkishWhiteZoom.jpg",
        ],
    },
    {
        id: 19,
        title : 'turkish flowers',
        color : 'white',
        type : 'embroidered',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 15200,
        customSelectionPrice : {
            shirt : 5120,
            back : 3030,
            dupatta : 5700,
            shalwar : 1350,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/turkishWhiteFlower1.jpg",
            "./assests/images/casuals/turkishWhiteFlower2.jpg",
        ],
    },
    {
        id: 20,
        title : 'vital range',
        color : 'white',
        type : 'embroidered',
        category : 'casual',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 15200,
        customSelectionPrice : {
            shirt : 5120,
            back : 3030,
            dupatta : 5700,
            shalwar : 1350,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/casuals/vitalRangeWhiteFull.jpg",
            "./assests/images/casuals/vitalRangeWhiteBack.jpg",
            "./assests/images/casuals/vitalRangeWhiteSide.jpg",
            "./assests/images/casuals/vitalRangeWhiteZoom.jpg",
        ],
    },
]