export const FormalProducts = [
    {
        id: 1,
        title : 'afreen range',
        color : 'mahroon',
        type : 'embrodered',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 17835,
        customSelectionPrice : {
            shirt : 4820,
            back : 5490,
            dupatta : 7525,
            shalwar : 0,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/afreenRangeMahroonFull.jpg",
            "./assests/images/formals/afreenRangeMahroonBack.jpg",
            "./assests/images/formals/afreenRangeMahroonSide.jpg",
            "./assests/images/formals/afreenRangeMahroonZoom.jpg",
        ],
    },
    {
        id: 2,
        title : 'antique jade',
        color : 'black',
        type : 'chiffon',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 36230,
        customSelectionPrice : {
            shirt : 4170,
            back : 4620,
            shawl : 27440,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/antiqueJadeBlackFull.jpg",
             "./assests/images/formals/antiqueJadeBlackBack.jpg",
             "./assests/images/formals/antiqueJadeBlackSide.jpg",
            "./assests/images/formals/antiqueJadeBlackZoom.jpg",
        ],
    },
    {
        id: 3,
        title : 'applique work',
        color : 'white',
        type : 'chiffon',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 27925,
        customSelectionPrice : {
            shirt : 23850,
            dupatta : 4075,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/appliqueWorkWhiteFull.jpg",
            "./assests/images/formals/appliqueWorkWhiteSide.jpg",
            "./assests/images/formals/appliqueWorkWhiteZoom.jpg",
        ],
    },
    {
        id: 4,
        title : 'applique work',
        color : 'white',
        type : 'chiffon',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 30350,
        customSelectionPrice : {
            shirt : 26150,
            dupatta : 4200,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/appliqueWorkWhiteFull11.jpg",
            "./assests/images/formals/appliqueWorkWhiteBack.jpg",
            "./assests/images/formals/appliqueWorkWhiteSide11.jpg",
            "./assests/images/formals/appliqueWorkWhiteZoom11.jpg",
        ],
    },
    {
        id: 5,
        title : 'badla work',
        color : 'brown',
        type : 'embroidered',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 19290,
        customSelectionPrice : {
            shirt : 5470,
            back : 6270,
            dupatta : 7550,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/badlaWorkBrownFront.jpg",
            "./assests/images/formals/badlaWorkBrownBack.jpg",
            "./assests/images/formals/badlaWorkBrownSide.jpg",
            "./assests/images/formals/badlaWorkBrownZoom.jpg",
        ],
    },
    {
        id: 6,
        title : 'badla work',
        color : 'red',
        type : 'embroidered',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 19290,
        customSelectionPrice : {
            shirt : 5470,
            back : 6270,
            dupatta : 7550,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/badlaWorkRedFull.jpg",
            "./assests/images/formals/badlaWorkRedBack.jpg",
            "./assests/images/formals/badlaWorkRedSide.jpg",
            "./assests/images/formals/badlaWorkRedZoom.jpg",
        ],
    },
    {
        id: 7,
        title : 'festive harmony',
        color : 'red',
        type : 'embroidered',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 19080,
        customSelectionPrice : {
            shirt : 5530,
            back : 5850,
            dupatta : 7700,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/festiveHarmonyRedFull.jpg",
            "./assests/images/formals/festiveHarmonyRedBack.jpg",
            "./assests/images/formals/festiveHarmonyRedSide.jpg",
            "./assests/images/formals/festiveHarmonyRedZoom.jpg",
        ],
    },
    {
        id: 8,
        title : 'flora vintage',
        color : 'beige',
        type : 'embroidered',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 16045,
        customSelectionPrice : {
            shirt : 10770,
            dupatta : 5275,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/floraVintageFull.jpg",
            "./assests/images/formals/floraVintageZoom.jpg",
        ],
    },
    {
        id: 9,
        title : 'gota work',
        color : 'green',
        type : 'embroidered',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 20450,
        customSelectionPrice : {
            shirt : 11175,
            dupatta : 9275,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/gotaWorkGreenFull.jpg",
            "./assests/images/formals/gotaWorkGreenBack.jpg",
            "./assests/images/formals/gotaWorkGreenSide.jpg",
            "./assests/images/formals/gotaWorkGreenZoom.jpg",
        ],
    },
    {
        id: 10,
        title : 'gull noor',
        color : 'green',
        type : 'embroidered',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 14100,
        customSelectionPrice : {
            shirt : 3390,
            back : 3510,
            dupatta : 5775,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            dupatta : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/gullNoorGreenFull.jpg",
            "./assests/images/formals/gullNoorGreenBack.jpg",
            "./assests/images/formals/gullNoorGreenSide.jpg",
            "./assests/images/formals/gullNoorGreenZoom.jpg",
        ],
    },
    {
        id: 11,
        title : 'gull noor',
        color : 'purple',
        type : 'embroidered',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 14015,
        customSelectionPrice : {
            shirt : 3390,
            back : 3750,
            dupatta : 5525,
            shalwar : 1350,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/gullNoorPurpleFull.jpg",
            "./assests/images/formals/gullNoorPurpleBack.jpg",
            "./assests/images/formals/gullNoorPurpleSide.jpg",
            "./assests/images/formals/gullNoorPurpleZoom.jpg",
        ],
    },
    {
        id: 12,
        title : 'mari gold',
        color : 'beige',
        type : 'embroidered',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 13843,
        customSelectionPrice : {
            shirt : 3750,
            back : 2817,
            dupatta : 5850,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/mariGoldBeigeFull.jpg",
            "./assests/images/formals/mariGoldBeigeBack.jpg",
            "./assests/images/formals/mariGoldBeigeSide.jpg",
            "./assests/images/formals/mariGoldBeigeZoom.jpg",
        ],
    },
    {
        id: 13,
        title : 'mari gold',
        color : 'green',
        type : 'embroidered',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 13843,
        customSelectionPrice : {
            shirt : 3750,
            back : 2817,
            dupatta : 5850,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/mariGoldGreenFull.jpg",
            "./assests/images/formals/mariGoldGreenBack.jpg",
            "./assests/images/formals/mariGoldGreenSide.jpg",
            "./assests/images/formals/mariGoldGreenZoom.jpg",
        ],
    },
    {
        id: 14,
        title : 'noor rang',
        color : 'beige',
        type : 'embroidered',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 11640,
        customSelectionPrice : {
            shirt : 2400,
            back : 2040,
            dupatta : 5775,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/noorRangBeigeFull.jpg",
            "./assests/images/formals/noorRangBeigeBack.jpg",
            "./assests/images/formals/noorRangBeigeSide.jpg",
            "./assests/images/formals/noorRangBeigeZoom.jpg",
        ],
    },
    {
        id: 15,
        title : 'noor rang',
        color : 'green',
        type : 'embroidered',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 14100,
        customSelectionPrice : {
            shirt : 6625,
            back : 0,
            dupatta : 6050,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/noorRangGreenFull.jpg",
            "./assests/images/formals/noorRangGreenBack.jpg",
            "./assests/images/formals/noorRangGreenSide.jpg",
            "./assests/images/formals/noorRangGreenZoom.jpg",
        ],
    },
    {
        id: 16,
        title : 'noor zindagi',
        color : 'grey',
        type : 'embroidered',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 12705,
        customSelectionPrice : {
            shirt : 2610,
            back : 2820,
            dupatta : 5850,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/noorZandgiGreyFull.jpg",
            "./assests/images/formals/noorZandgiGreyBack.jpg",
            "./assests/images/formals/noorZandgiGreySide.jpg",
            "./assests/images/formals/noorZandgiGreyZoom.jpg",
        ],
    },
    {
        id: 17,
        title : 'noor zindagi',
        color : 'grey',
        type : 'embroidered',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 14150,
        customSelectionPrice : {
            shirt : 3250,
            back : 3825,
            dupatta : 5650,
            shalwar : 1425,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/noorZandgiGreyFull11.jpg",
            "./assests/images/formals/noorZandgiGreyBack11.jpg",
            "./assests/images/formals/noorZandgiGreySide11.jpg",
            "./assests/images/formals/noorZandgiGreyZoom11.jpg",
        ],
    },
    {
        id: 18,
        title : 'phool pho',
        color : 'red',
        type : 'embroidered',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 15200,
        customSelectionPrice : {
            shirt : 5120,
            back : 3030,
            dupatta : 5700,
            shalwar : 1350,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/phoolRhoRedFull.jpg",
            "./assests/images/formals/phoolRhoRedBack.jpg",
            "./assests/images/formals/phoolRhoRedSide.jpg",
            "./assests/images/formals/phoolRhoRedZoom.jpg",
        ],
    },
    {
        id: 19,
        title : 'radiant rang',
        color : 'aqua',
        type : 'embroidered',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 15200,
        customSelectionPrice : {
            shirt : 5120,
            back : 3030,
            dupatta : 5700,
            shalwar : 1350,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/radiantRangAquaFull.jpg",
            "./assests/images/formals/radiantRangAquaBack.jpg",
            "./assests/images/formals/radiantRangAquaSide.jpg",
            "./assests/images/formals/radiantRangAquaZoom.jpg",
        ],
    },
    {
        id: 20,
        title : 'zardoi',
        color : 'black',
        type : 'embroidered',
        category : 'formal',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 15200,
        customSelectionPrice : {
            shirt : 5120,
            back : 3030,
            dupatta : 5700,
            shalwar : 1350,
        },
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/formals/zardoiBlackFull.jpg",
            "./assests/images/formals/zardoiBlackBack.jpg",
            "./assests/images/formals/zardoiBlackSide.jpg",
            "./assests/images/formals/zardoiBlackZoom.jpg",
        ],
    },
]