export const PrintProducts = [
    {
        id: 1,
        title : 'printed',
        color : 'pink',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 7800,
        size : '3-pieces',
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/prints/printedPinkFront.jpg",
            "./assests/images/prints/printedPinkBack.jpg",
            "./assests/images/prints/printedPinkSide.jpg",
            "./assests/images/prints/printedPinkZoom.jpg",
        ],
    },
    {
        id: 2,
        title : 'printed',
        color : 'beige',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 4330,
        size : '3-pieces',
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/prints/printedBeigeFront.jpg",
             "./assests/images/prints/printedBeigeBack.jpg",
             "./assests/images/prints/printedBeigeSide.jpg",
            "./assests/images/prints/printedBeigeZoom.jpg",
        ],
    },
    {
        id: 3,
        title : 'printed',
        color : 'yellow',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 17600,
        size : '3-pieces',
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/prints/printedYellowFront.jpg",
            "./assests/images/prints/printedYellowBack.jpg",
            "./assests/images/prints/printedYellowSide.jpg",
            "./assests/images/prints/printedYellowZoom.jpg",
        ],
    },
    {
        id: 4,
        title : 'printed',
        color : 'red',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 5000,
        size : '3-pieces',
        images : [
            "./assests/images/prints/printedRedFront.jpg",
            "./assests/images/prints/printedRedBack.jpg",
            "./assests/images/prints/printedRedSide.jpg",
            "./assests/images/prints/printedRedZoom.jpg",
        ],
    },
    {
        id: 5,
        title : 'printed',
        color : 'ferozi',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 7800,
        size : '3-pieces',
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/prints/printedFeroziFront.jpg",
            "./assests/images/prints/printedFeroziBack.jpg",
            "./assests/images/prints/printedFeroziSide.jpg",
            "./assests/images/prints/printedFeroziZoom.jpg",
        ],
    },
    {
        id: 6,
        title : 'printed',
        color : 'grey',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 4250,
        size:'3-pieces',
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/prints/printedGreyFront.jpg",
            "./assests/images/prints/printedGreyBack.jpg",
            "./assests/images/prints/printedGreySide.jpg",
            "./assests/images/prints/printedGreyZoom.jpg",
        ],
    },
    {
        id: 7,
        title : 'printed',
        color : 'black',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 4430,
        size : '3-pieces',
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/prints/printedBlackFront.jpg",
            "./assests/images/prints/printedBlackBack.jpg",
            "./assests/images/prints/printedBlackSide.jpg",
            "./assests/images/prints/printedBlackZoom.jpg",
        ],
    },
    {
        id: 8,
        title : 'printed',
        color : 'green',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 3650,
        size:'3-pieces',
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/prints/printedGreenFront.jpg",
            "./assests/images/prints/printedGreenBack.jpg",
            "./assests/images/prints/printedGreenZoom.jpg",
        ],
    },
    {
        id: 9,
        title : 'printed',
        color : 'black',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 3650,
        size : '3-pieces',
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/prints/printedBlackFront11.jpg",
            "./assests/images/prints/printedBlackBack11.jpg",
            "./assests/images/prints/printedBlackSide11.jpg",
            "./assests/images/prints/printedBlackZoom11.jpg",
        ],
    },
    {
        id: 10,
        title : 'printed',
        color : 'yellow',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 4090,
        size:'3-pieces',
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/prints/printedYellowFront11.jpg",
            "./assests/images/prints/printedYellowBack11.jpg",
            "./assests/images/prints/printedYellowSide11.jpg",
        ],
    },
    {
        id: 11,
        title : 'printed',
        color : 'pink',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 4870,
        size:'3-pieces',
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/prints/printedPinkFront11.jpg",
            "./assests/images/prints/printedPinkBack11.jpg",
            "./assests/images/prints/printedPinkSide11.jpg",
            "./assests/images/prints/printedPinkZoom11.jpg",
        ],
    },
    {
        id: 12,
        title : 'printed',
        color : 'blue',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 4090,
        size:'3-pieces',
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/prints/printedBlueFront.jpg",
            "./assests/images/prints/printedBlueBack.jpg",
            "./assests/images/prints/printedBlueSide.jpg",
            "./assests/images/prints/printedBlueZoom.jpg",
        ],
    },
    {
        id: 13,
        title : 'printed',
        color : 'pink',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 7800,
        size : '3-pieces',
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/prints/printedPinkFront.jpg",
            "./assests/images/prints/printedPinkBack.jpg",
            "./assests/images/prints/printedPinkSide.jpg",
            "./assests/images/prints/printedPinkZoom.jpg",
        ],
    },
    {
        id: 14,
        title : 'printed',
        color : 'beige',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 4330,
        size : '3-pieces',
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/prints/printedBeigeFront.jpg",
             "./assests/images/prints/printedBeigeBack.jpg",
             "./assests/images/prints/printedBeigeSide.jpg",
            "./assests/images/prints/printedBeigeZoom.jpg",
        ],
    },
    {
        id: 15,
        title : 'printed',
        color : 'yellow',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 17600,
        size : '3-pieces',
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/prints/printedYellowFront.jpg",
            "./assests/images/prints/printedYellowBack.jpg",
            "./assests/images/prints/printedYellowSide.jpg",
            "./assests/images/prints/printedYellowZoom.jpg",
        ],
    },
    {
        id: 16,
        title : 'printed',
        color : 'red',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 5000,
        size : '3-pieces',
        images : [
            "./assests/images/prints/printedRedFront.jpg",
            "./assests/images/prints/printedRedBack.jpg",
            "./assests/images/prints/printedRedSide.jpg",
            "./assests/images/prints/printedRedZoom.jpg",
        ],
    },
    {
        id: 17,
        title : 'printed',
        color : 'ferozi',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 7800,
        size : '3-pieces',
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/prints/printedFeroziFront.jpg",
            "./assests/images/prints/printedFeroziBack.jpg",
            "./assests/images/prints/printedFeroziSide.jpg",
            "./assests/images/prints/printedFeroziZoom.jpg",
        ],
    },
    {
        id: 18,
        title : 'printed',
        color : 'grey',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 4250,
        size:'3-pieces',
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/prints/printedGreyFront.jpg",
            "./assests/images/prints/printedGreyBack.jpg",
            "./assests/images/prints/printedGreySide.jpg",
            "./assests/images/prints/printedGreyZoom.jpg",
        ],
    },
    {
        id: 19,
        title : 'printed',
        color : 'black',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 4430,
        size : '3-pieces',
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/prints/printedBlackFront.jpg",
            "./assests/images/prints/printedBlackBack.jpg",
            "./assests/images/prints/printedBlackSide.jpg",
            "./assests/images/prints/printedBlackZoom.jpg",
        ],
    },
    {
        id: 20,
        title : 'printed',
        color : 'green',
        type : 'printed',
        category : 'print',
        fabric : 'lawn',
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 3650,
        size:'3-pieces',
        description : {
            shirt  : '1 Meter',
            back : '1.5 Meter',
            dupatta : '2.5 Meter',
            shalwar : '2.5 Meter',
        },
        images : [
            "./assests/images/prints/printedGreenFront.jpg",
            "./assests/images/prints/printedGreenBack.jpg",
            "./assests/images/prints/printedGreenZoom.jpg",
        ],
    },
]