export const ShawlProducts = [
    {
        id: 1,
        title : 'net applique shawl',
        color : 'black',
        type : '',
        category : 'shawl',
        fabric : 'lawn' ,
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 9300,
        description : "net applique shawl shawl: embroidered dc air jet lawn 2.5 meter",
        images : [
            "./assests/images/shawls/ShawlWhiteFull.jpg",
            "./assests/images/shawls/ShawlWhiteZoom.jpg",
        ],
    },
    {
        id: 2,
        title : 'gul-e-lala shawl',
        color : 'black',
        type : '',
        category : 'shawl',
        fabric : 'lawn' ,
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 82620,
        description : "net applique shawl shawl: embroidered dc air jet lawn 2.5 meter",
        images : [
            "./assests/images/shawls/ShawlBlackFull11.jpg",
            "./assests/images/shawls/ShawlBlackZoom11.jpg",
        ],
    },
    {
        id: 3,
        title : 'net applique shawl',
        color : 'black',
        type : '',
        category : 'shawl',
        fabric : 'lawn' ,
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 9300,
        description : "net applique shawl shawl: embroidered dc air jet lawn 2.5 meter",
        images : [
            "./assests/images/shawls/ShawlBlackFull.jpg",
            "./assests/images/shawls/ShawlBlackZoom.jpg",
        ],
    },
    {
        id: 4,
        title : 'ethic legacy - 1 shawl',
        color : 'beige',
        type : '',
        category : 'shawl',
        fabric : 'lawn' ,
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 17774,
        description : "net applique shawl shawl: embroidered dc air jet lawn 2.5 meter",
        images : [
            "./assests/images/shawls/ShawlBeigeFull.jpg",
            "./assests/images/shawls/ShawlBeigeZoom.jpg",
        ],
    },
    {
        id: 5,
        title : 'tribal fusion shawl',
        color : 'navy blue',
        type : '',
        category : 'shawl',
        fabric : 'lawn' ,
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 21675,
        description : "net applique shawl shawl: embroidered dc air jet lawn 2.5 meter",
        images : [
            "./assests/images/shawls/ShawlNavyBlueFull.jpg",
            "./assests/images/shawls/ShawlNavyBlueZoom.jpg",
        ],
    },
    {
        id: 6,
        title : 'golden empire shawl',
        color : 'black',
        type : '',
        category : 'shawl',
        fabric : 'lawn' ,
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 27440,
        description : "net applique shawl shawl: embroidered dc air jet lawn 2.5 meter",
        images : [
            "./assests/images/shawls/ShawlBlackFull22.jpg",
            "./assests/images/shawls/ShawlBlackZoom22.jpg",
        ],
    },
    {
        id: 7,
        title : 'red rose shawl',
        color : 'off white',
        type : '',
        category : 'shawl',
        fabric : 'lawn' ,
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 10838,
        description : "net applique shawl shawl: embroidered dc air jet lawn 2.5 meter",
        images : [
            "./assests/images/shawls/ShawlOffWhiteFull.jpg",
            "./assests/images/shawls/ShawlOffWhiteZoom.jpg",
        ],
    },
    {
        id: 8,
        title : 'calor pick shawl',
        color : 'blue',
        type : '',
        category : 'shawl',
        fabric : 'lawn' ,
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 20375,
        description : "net applique shawl shawl: embroidered dc air jet lawn 2.5 meter",
        images : [
            "./assests/images/shawls/ShawlBlueFull11.jpg",
            "./assests/images/shawls/ShawlBlueZoom11.jpg",
        ],
    },
    {
        id: 9,
        title : 'kani bagh shawl',
        color : 'beige',
        type : '',
        category : 'shawl',
        fabric : 'lawn' ,
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 16040,
        description : "net applique shawl shawl: embroidered dc air jet lawn 2.5 meter",
        images : [
            "./assests/images/shawls/ShawlBeigeFull11.jpg",
            "./assests/images/shawls/ShawlBeigeZoom11.jpg",
        ],
    },
    {
        id: 10,
        title : 'sher shah shawl',
        color : 'green',
        type : '',
        category : 'shawl',
        fabric : 'lawn' ,
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 76500,
        description : "net applique shawl shawl: embroidered dc air jet lawn 2.5 meter",
        images : [
            "./assests/images/shawls/ShawlGreenFull.jpg",
            "./assests/images/shawls/ShawlGreenZoom.jpg",
        ],
    },
    {
        id: 11,
        title : 'nakkashi range shawl',
        color : 'beige',
        type : '',
        category : 'shawl',
        fabric : 'lawn' ,
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 16388,
        description : "net applique shawl shawl: embroidered dc air jet lawn 2.5 meter",
        images : [
            "./assests/images/shawls/ShawlBeigeFull22.jpg",
            "./assests/images/shawls/ShawlBeigeZoom22.jpg",
        ],
    },
    {
        id: 12,
        title : 'fusion art shawl',
        color : 'beige',
        type : '',
        category : 'shawl',
        fabric : 'lawn' ,
        qunatity : '20',
        season  :'summer',
        inStock : true,
        completeSuitPrice : 17774,
        description : "net applique shawl shawl: embroidered dc air jet lawn 2.5 meter",
        images : [
            "./assests/images/shawls/ShawlBeigeFull33.jpg",
            "./assests/images/shawls/ShawlBeigeZoom33.jpg",
        ],
    },
]